### ISSUE TITLE
Fallback for sites with out Open Graph information set

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/fancylinks#1]
If a site doesn't have the open graph stuff set we need to set a fallback.

Maybe the favicon for the image and meta description for the text.

**Comment by Mamaduka** [comment]
@nickhamze parser checks for description, OG and Twitter. I think if the image isn't specified we should hide the card media elements.

**Comment by nickhamze** [comment]
ok, that works.

**Comment by Mamaduka** [comment]
Awesome. Already pushed that fix, with some other minor changes.

**Comment by nickhamze** [comment]
If I add a link and then change it to a different one it sometimes uses the information from the first link if the second site doesn't have that information set.

Try using zaroty.com then change it to nickhamze.com. The zaroty image stays even though there isn't an image specified.

**Comment by Mamaduka** [comment]
The issue should be fixed now. Metadata results are cached in transients, you might want to delete them before testing the last fix.

"Transients Manager" plugin should help with that - https://wordpress.org/plugins/transients-manager/
