### ISSUE TITLE
Looks a little broken in 5.4

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/fancylinks#4]
@Mamaduka The block looks a little broken in 5.4. I think some of the markup must have changed.

<img width="667" alt="Screen Shot 2020-03-25 at 4 57 07 PM" src="https://user-images.githubusercontent.com/158918/77589482-bef5b400-6eb9-11ea-9e1b-bb957afa7853.png">

The secrets are added so you can push the fixed version when you have it ready.

**Comment by Mamaduka** [comment]
Fixed the issue and deployed changes to WP.org.
